[project]

name = "shm_ugw_analysis"
description = "Data analysis for UGW data for SHM."
version = "0.1.0"
requires-python = ">=3.10.0,<=3.10.99"
license = {file = "LICENSE"}

[build-system]
requires = ["setuptools>=62.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
